# Generated by Django 3.2.5 on 2021-07-12 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=56)),
                ('last_name', models.CharField(max_length=56)),
                ('agency', models.CharField(max_length=256)),
                ('contact_number', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=256)),
                ('street', models.CharField(max_length=256)),
                ('house_number', models.SmallIntegerField()),
                ('flat_number', models.SmallIntegerField()),
                ('post_code', models.IntegerField()),
                ('flat_surface', models.SmallIntegerField()),
                ('basic_flat_rental_cost', models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=56)),
                ('last_name', models.CharField(max_length=56)),
                ('pesel', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('contact_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rentier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=56)),
                ('last_name', models.CharField(max_length=56)),
                ('pesel', models.IntegerField()),
                ('contact_number', models.IntegerField()),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_room_rental_cost', models.SmallIntegerField(null=True)),
                ('room_surface', models.SmallIntegerField()),
                ('room_number', models.IntegerField()),
                ('flat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flat_manager.flat')),
            ],
        ),
        migrations.CreateModel(
            name='LeaseAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.IntegerField(null=True, unique=True)),
                ('end_of_contract', models.DateField()),
                ('contract_date', models.DateField()),
                ('date_of_payment', models.SmallIntegerField(null=True)),
                ('monthly_cost', models.IntegerField()),
                ('agent_provision', models.IntegerField()),
                ('number_of_keys', models.SmallIntegerField(null=True)),
                ('damage_desc', models.CharField(max_length=512)),
                ('deposit', models.IntegerField(null=True)),
                ('equipment', models.CharField(max_length=512)),
                ('flat', models.ManyToManyField(to='flat_manager.Flat')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flat_manager.owner')),
                ('rentier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flat_manager.rentier')),
                ('rooms', models.ManyToManyField(to='flat_manager.Room')),
            ],
        ),
        migrations.AddField(
            model_name='flat',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flat_manager.owner'),
        ),
    ]
